### ISSUE TITLE
Consider mirroring smalltalk-mode from GNU Smalltalk

### ISSUE THREAD

**Issue by Wilfred** [emacsmirror/.github#1]
Hi @tarsius 

Would you be willing to add smalltalk-mode.el to the emacsmirror or the emacsorphanage?

GNU Smalltalk provides this Emacs mode. I've sent the patch to their mailing list: http://lists.gnu.org/archive/html/help-smalltalk/2017-08/msg00000.html but the project is very lightly maintained: https://github.com/gnu-smalltalk/smalltalk/commits/master (as far as I can tell).

I'd like to make this available on MELPA, and I thought one of your Emacs organisations would be a good fit. What do you think?

**Comment by tarsius** [comment]
> Would you be willing to add smalltalk-mode.el to the emacsmirror or the emacsorphanage?

Yes, but it would be better if the elisp was maintained in its own repository. I try to only mirror the elisp part, so I sometimes use a subtree filter to import just the relevant directory. But in this case that would not work because the elisp is placed at the top-level, so I would have to use the "minority" method, which just downloads the current version of the file itself, which would lose all commit messages. Does this mode also work with other smalltalk implementations? If so that would be another reason to put this in a separate repostiory.

Also the header (and possibly other things) would have to be updated to match the conventions before it can be added Melpa.

All in all I think it would be best if you, or someone else who is interested in this mode, would take over as maintainer and maintain the elisp in a separate repository. After asking the current maintainers of course.

**Comment by Wilfred** [comment]
> Does this mode also work with other smalltalk implementations?

There's nothing specific to GNU smalltalk here: any smalltalk implementation will have the same syntax. For example, I've been using it to view files dumped from Pharo. It is most useful on GNU Smalltalk though, as most other Smalltalk implementations have an integrated IDE.

> Also the header (and possibly other things) would have to be updated to match the conventions before it can be added Melpa.

Yep, I've done this on my branch: https://github.com/Wilfred/gnu-smalltalk/tree/refactor_emacs_mode (though I see you've spotted this already).

The mode exists, it works and it's useful. I'm hoping that GNU Smalltalk is just quiet rather than inactive -- forking seems a little antisocial. I was hoping to use the orphanage/attic to communicate that I'm not actively maintaining this mode.

**Comment by tarsius** [comment]
> The mode exists, it works and it's useful. I'm hoping that GNU Smalltalk is just quiet rather than inactive -- forking seems a little antisocial. I was hoping to use the orphanage/attic to communicate that I'm not actively maintaining this mode.

I don't think that adding the package to the orphanage would be friendlier than maintaining a fork under your own account. Either way, I don't think it is "antisocial" to do it after you have made a reasonable effort to engage the official maintainers and have given them enough time to respond in case they are busy.

I am not ruling out adding this to the orphanage, but I think there are better options, including adding it to GNU Elpa.

**Comment by Wilfred** [comment]
FWIW, it looks like my patch may yet land in GNU Smalltalk, which would be the ideal solution: http://lists.gnu.org/archive/html/help-smalltalk/2017-08/msg00004.html

**Comment by tarsius** [comment]
> which would be the ideal solution

It's a good solution. The ideal situation would be if someone maintained it who is an Emacs user and who is also exited about doing it (as opposed to just doing it because nobody else does). :wink:

If this does not pan out, then feel free to reopen this issue.

Cheers!
