### ISSUE TITLE
Update mirrors for emacs.git packages

### ISSUE THREAD

**Issue by kljohann** [emacsmirror/.github#10]
Some packages are developed inside the Emacs repo but also made available via GNU ELPA. It's very convenient that there are @emacsmirror repos, for example for use via [borg](https://github.com/emacscollective/borg). Thanks for working on both, @tarsius! As far as I understand, syncing of these repos is triggered manually, though? For example,
- eldoc is 1.8.0 < 1.11.0,
- flymake is 1.0.9 < 1.2.1,
- project is 0.5.1 < 0.8.1, and
- xref 1.0.2 < 1.3.2.

A recent version of flymake will soon be required to use [eglot](https://github.com/joaotavora/eglot). Could you please trigger an update for these packages?

**Comment by tarsius** [comment]
> As far as I understand, syncing of these repos is triggered manually, though?

Yes; and it is code that has never run before, so... I'll do it when I have less things on my plate.

**Comment by kljohann** [comment]
Thanks, sounds great. If I can help in some way, please let me know.

**Comment by tarsius** [comment]
I regret to inform you that I have given up on extracting the history of core packages.

`git filter-repo`, the tool that this functionality was built on, just isn't efficient and reliable enough to continuously extract history from the emacs repository. I had hopes that this would improve enough to remove this limiation, but that hasn't happened yet. Here are some outstanding issues: https://github.com/newren/git-filter-repo/issues/created_by/tarsius.

But it's not just the import tool. The emacs repository also has a very messy history. For example, here are a few very bad merges, that duplicate thousands of commits. Those could probably be filtered out using `git-replace`, but that is a whole other can of worms.

I am also not sure how useful these repositories with filtered history would be. They couldn't be use to contribute the the respective packages, the way a proper clone of the upstream repository can be used.

I have been using the development version of emacs for the past few years, so I haven't thought about it too much, but here are some ideas on how to install these packages when using a released emacs. (1) Just use `package.el`. (2) Create a directory that contains symlinks to core libraries in a checkout of emacs' master branch. Compile the files in that directory and add it to the `load-path`, but only when not using the development version. Some tooling around that idea would be nice, but since I currently have no need for that myself and am quite busy with other things, I probably won't implement that.

> If I can help in some way, please let me know.

Well, you could work on improving `git filter-repo`, but I expect this would be quite a bit of work.

**Comment by kljohann** [comment]
Thanks for giving it a try and letting me know of the alternatives!
