### ISSUE TITLE
cmake-mode need to update

### ISSUE THREAD

**Issue by Eason0210** [emacsmirror/.github#11]
Recently, cmake-mode upstream have 2 commits ahead of [emacsmirror/cmake-mode](https://github.com/emacsmirror/cmake-mode)

1. cmake-mode on melpa:  https://melpa.org/#/cmake-mode
2. cmake-mode.el on cmake project: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Auxiliary/cmake-mode.el

**Comment by tarsius** [comment]
It's one of the packages that no longer get updated automatically because doing so takes too long. Or rather, just checking whether there are any updates takes too long, even when there are no new commits. `git filter-repo` does not live up to its marketing. Last night initiated an update before going to bed.

So I am afraid you'll have to ping me again when there is another update.

If you are involved in the development of this package, then please consider maintaining it in a separate repository. (Also see https://github.com/melpa/melpa/issues/5361.)
