### ISSUE TITLE
Please consider moving to an ethical repository hosting

### ISSUE THREAD

**Issue by AkibAzmain** [emacsmirror/.github#12]
**MS employees, please stay away.**

---

Copilot is indexing the repository on GitHub to help build proprietary software.  I don't support this in any way, and I don't want to feed my hard work to Copilot.

Please consider moving to some repository hosting like SourceHut, any of the public Gitea instances (Codeberg is the most popular).  Even GitLab is better than GitHub (only right now).  Moving shouldn't be too hard, since `emacsmirror` and `emacsattic` are not intended for people's interaction.

If moving not possible, I request you to remove my packages from this archive (though GPL allows you to feed my code to Copilot).

---

> Thanks for your interest in contributing to this package.
> 
> This repository is only a mirror.  Please do not open an issue here.  Instead figure out where the upstream repository is and open an issue there.  If the upstream repository is located on Github, then you should see a link "forked from somebody-else/this-project" should be visible above and that link should take you there.

No, this isn't a package mirror at all.  Maybe you should consider removing this message for this repository.

**Comment by tarsius** [comment]
> Moving shouldn't be too hard, since `emacsmirror` and `emacsattic` are not intended for people's interaction.

Moving would we much more work than you imagine, among other things because it *is* intended for certain kinds of user "interaction".

(A nice property of the Emacsmirror is that all packages are available at `https://github.com/emacsmirror/PACKAGENAME`; users do not have know what forge upstream uses. Self-hosted git repositories also go down quite often, more often than Github/Codeberg/etc. My package manager `borg` falls back to using the mirror if the upstream is not available. Some users have added repositories from here as remotes.)

I am considering *also* making "all" repositories available on other forges, allowing users to fork on the platform(s) that they happen to already use.

> If moving not possible, I request you to remove my packages from this archive (though GPL allows you to feed my code to Copilot).

Done.

It's mostly a symbolic act tough. At least the current version of your code has already been absorbed. And it is unfortunate that there are now package "on the Emacsmirror", that are not actually available from the Emacsmirror.

**Comment by AkibAzmain** [comment]
> > Moving shouldn't be too hard, since `emacsmirror` and `emacsattic` are not intended for people's interaction.
> 
> Moving would we much more work than you imagine, among other things because it _is_ intended for certain kinds of user "interaction".
> 
> (A nice property of the Emacsmirror is that all packages are available at `https://github.com/emacsmirror/PACKAGENAME`; users do not have know what forge upstream uses. Self-hosted git repositories also go down quite often, more often than Github/Codeberg/etc. My package manager `borg` falls back to using the mirror if the upstream is not available. Some users have added repositories from here as remotes.)
> 
> I am considering _also_ making "all" repositories available on other forges, allowing users to fork on the platform(s) that they happen to already use.
> 

Then I have a idea.  Migrate to some other host, and leave this as is (since Copliot has already eaten these).  No links would break.  And give a notice everywhere to update the links.

> > If moving not possible, I request you to remove my packages from this archive (though GPL allows you to feed my code to Copilot).
> 
> Done.
> 
> It's mostly a symbolic act tough. At least the current version of your code has already been absorbed. And it is unfortunate that there are now package "on the Emacsmirror", that are not actually available from the Emacsmirror.

Thanks.  We can't change things that has already happened, but we can change what's going to happen.
