### ISSUE TITLE
Frequency of package updates

### ISSUE THREAD

**Issue by grtcdr** [emacsmirror/.github#13]
Hi,

I was wondering what the *update frequency* of packages for the Emacsmirror is, forgive me if this the wrong place to ask.

I noticed that some packages, e.g. [darkman](https://github.com/emacsmirror/darkman) [^1], lag behind by a month or possibly more while others are synced (e.g. denote) shortly after they are updated.

Thank you so much for this creating this project and auxiliary tools such as Borg and Epkg that I and many others use every day. I really appreciate the level of control and stability that they provide.

- Speaking of Borg, should I just update the `url` of the submodule that's lagging behind to point to upstream rather than the mirrored repository?

[^1]: Its last update on Emacsmirror was made on April 15, 2023 yet it has seen 18 commits since then).

**Comment by tarsius** [comment]
> I was wondering what the update frequency of packages for the Emacsmirror is

About once per week for packages hosted on Github. Most other packages every other week. (Updating from Github is cheaper because the API can be used to retrieve a list of repositories that actually have new commits. Repositories hosted elsewhere have to be pulled, usually to learn that there is nothing new, and that is much more expensive. There is a third set of packages that are updated even less often, e.g., those hosted on the Emacswiki, because here history rewriting is required.

This is done semi-automatically. Automation and frequency may increase in the future.

> I noticed that some packages, e.g. [darkman](https://github.com/emacsmirror/darkman)

Nowadays I usually don't add any new packages until they are added to Melpa or they appear as a new dependency of a package that is already mirrored. It seems I added this package manually.

It appears that I first mirrored the package from Github. After I saw this on your profile

> Computer science student and free software developer, **recently moved to Sourcehut.**

I concluded that I should mirror the package from there instead. (The fork relationship survived that "change of upstream" performed on the mirror.)

You haven't pushed these commits to Sourcehut yet, and since we mirror it from there, they haven't made it onto the Emacsmirror yet either.

So I assume I should mirror from Github then? Please make it clear in the README, which repository is only a (possibly outdated) copy.

**Comment by grtcdr** [comment]
Thank you for the quick response,

> About once per week for packages hosted on Github. Most other packages every other week. (Updating from Github is cheaper because the API can be used to retrieve a list of repositories that actually have new commits. Repositories hosted elsewhere have to be pulled, usually to learn that there is nothing new, and that is much more expensive. There is a third set of packages that are updated even less often, e.g., those hosted on the Emacswiki, because here history rewriting is required.

Oh, gotcha. Thanks for the clarification. I'll have a look around the project to see how your tools fit in and communicate with other providers regarding the automation process.

> Nowadays I usually don't add any new packages until they are added to Melpa or they appear as a new dependency of a package that is already mirrored. It seems I added this package manually.

It was initially, and after some hesitation on my part, added to MELPA on [March 6](https://github.com/melpa/melpa/commit/4f44720c122daf7e5dafb74effeb690b00b8167f). Your fork appears to have been made on the same day, per the GitHub API. I don't know whether that happened before or after the merge.

> I concluded that I should mirror the package from there instead. (The fork relationship survived that "change of upstream" performed on the mirror.)

Yes, that was indeed the correct decision. I wish migrations could be less of a pain for the maintainers involved. Thank you for taking care of this often tedious process. I'm always around if a project of mine is causing any trouble, so please free to contact me at any time.

> You haven't pushed these commits to Sourcehut yet, and since we mirror it from there, they haven't made it onto the Emacsmirror yet either. So I assume I should mirror from Github then? Please make it clear in the README, which repository is only a (possibly outdated) copy.

I've been pushing exclusively to Sourcehut, every repository of mine on GitHub has been archived with a notice pointing to the new remote. Is this not the case for you?
