### ISSUE TITLE
AuCTeX git repopage

### ISSUE THREAD

**Issue by jabranham** [emacsmirror/.github#5]
`epkg-describe-package` current lists https://git.savannah.gnu.org/cgit/emacs/elpa.git/log/?h=externals/auctex as the repopage for AuCTeX, but that's the ELPA mirror of the development repository, which is actually at https://git.savannah.gnu.org/cgit/auctex.git

git clone https://git.savannah.gnu.org/git/auctex.git

Thanks!

**Comment by tarsius** [comment]
For packages that have their own branch on Elpa I usually prefer that over the upstream repository because often development has stopped upstream while bugs are still being fixed in Elpa.

But in this case upstream is active, so I have switched to that. (And looking at some old notes I found an entry explaining why I "had done" that. 😉 )

**Comment by jabranham** [comment]
All that makes sense, thanks!
